  stages:
  - build
  - push
  
  variables:
  CONTAINER_IMAGE: registry.cn-hangzhou.aliyuncs.com:qiaozhuangzhuang-${CI_COMMIT_SHORT_SHA}
  
  image-build:
    image: docker
    stage: build
    only:
    - master
    script:
      - apk update && apk add git
      - git clone https://github.com/moleculerjs/moleculer-examples.git
      - cd moleculer-examples/blog
      - docker build -t ${CONTAINER_IMAGE} .
  image-push:
    stage: push
    only:
    - master
    before_script:
      - docker login -u xiaoyu-dev -p YMaFmi8u
    script:
      - docker push ${CONTAINER_IMAGE}
    
